model: mistralai/mistral-large-2512
supervisor_model: mistralai/mistral-large-2512
worker_model: mistralai/mistral-small-3.2-24b-instruct
temperature: 0.0
top_p: 0.9
presence_penalty: 0.0
frequency_penalty: 0.0
max_output_tokens: 256
request_timeout_s: 60
max_retries: 3
rate_limit_rps: 2
headers:
  http_referer: https://example.org/mas
  x_title: MAS-Orchestrator

supervisor_fallback_model: mistralai/mistral-medium-3.1
worker_fallback_model: mistralai/mistral-medium-3.1
supervisor_secondary_fallback_model: null
worker_secondary_fallback_model: null

swarm_models:
  - mistralai/mistral-large-2512
  - mistralai/mistral-medium-3.1
  - mistralai/mistral-small-3.2-24b-instruct
swarm_min_responses: 2
swarm_per_model_timeout: 120
swarm_overall_timeout: 300


